# YOLOv3-tiny-det model_config.

scale = "l"

[scales.l]
depth = 1.00
width = 1.00
summary = "yolov3-tiny-det model"

# ----------------------------backbone---------------------------------
[[network]]
# 0
type = "entry"
module = "Conv"
repeat = 1
from = [-1]
args.in_channels = 3
args.out_channels = 16
args.kernel_size = 3
args.stride = 1

[[network]]
# 1-P1/2
type = "flow"
module = "torch.nn.MaxPool2d"
repeat = 1
from = [-1]
args.kernel_size = 2
args.stride = 2
args.padding = 0

[[network]]
# 2
type = "flow"
module = "Conv"
repeat = 1
from = [-1]
args.in_channels = 16
args.out_channels = 32
args.kernel_size = 3
args.stride = 1

[[network]]
# 3-P2/4
type = "flow"
module = "torch.nn.MaxPool2d"
repeat = 1
from = [-1]
args.kernel_size = 2
args.stride = 2
args.padding = 0

[[network]]
# 4
type = "flow"
module = "Conv"
repeat = 1
from = [-1]
args.in_channels = 32
args.out_channels = 64
args.kernel_size = 3
args.stride = 1

[[network]]
# 5-P3/8
type = "flow"
module = "torch.nn.MaxPool2d"
repeat = 1
from = [-1]
args.kernel_size = 2
args.stride = 2
args.padding = 0

[[network]]
# 6
type = "flow"
module = "Conv"
repeat = 1
from = [-1]
args.in_channels = 64
args.out_channels = 128
args.kernel_size = 3
args.stride = 1

[[network]]
# 7-P4/16
type = "flow"
module = "torch.nn.MaxPool2d"
repeat = 1
from = [-1]
args.kernel_size = 2
args.stride = 2
args.padding = 0

[[network]]
# 8
type = "flow"
module = "Conv"
repeat = 1
from = [-1]
args.in_channels = 128
args.out_channels = 256
args.kernel_size = 3
args.stride = 1

[[network]]
# 9-P5/32
type = "flow"
module = "torch.nn.MaxPool2d"
repeat = 1
from = [-1]
args.kernel_size = 2
args.stride = 2
args.padding = 0

[[network]]
# 10
type = "flow"
module = "Conv"
repeat = 1
from = [-1]
args.in_channels = 256
args.out_channels = 512
args.kernel_size = 3
args.stride = 1

[[network]]
# 11
type = "flow"
module = "torch.nn.ZeroPad2d"
repeat = 1
from = [-1]
args.padding = [0, 1, 0, 1]

[[network]]
# 12
type = "flow"
module = "torch.nn.MaxPool2d"
repeat = 1
from = [-1]
args.kernel_size = 2
args.stride = 1
args.padding = 0

# ----------------------------------head--------------------------------------
[[network]]
# 13
type = "flow"
module = "Conv"
repeat = 1
from = [-1]
args.in_channels = 512
args.out_channels = 1024
args.kernel_size = 3
args.stride = 1

[[network]]
# 14
type = "flow"
module = "Conv"
repeat = 1
from = [-1]
args.in_channels = 1024
args.out_channels = 256
args.kernel_size = 1
args.stride = 1

[[network]]
# 15 (P5/32-large)
type = "flow"
module = "Conv"
repeat = 1
from = [-1]
args.in_channels = 256
args.out_channels = 512
args.kernel_size = 3
args.stride = 1

[[network]]
# 16
type = "flow"
module = "Conv"
repeat = 1
from = [14]
args.in_channels = 256
args.out_channels = 128
args.kernel_size = 1
args.stride = 1

[[network]]
# 17
type = "flow"
module = "torch.nn.Upsample"
repeat = 1
from = [-1]
args.scale_factor = 2
args.mode = "nearest"

[[network]]
# 18 cat backbone P4
type = "flow"
module = "Concat"
repeat = 1
from = [-1, 8]

[[network]]
# 19 (P4/16-medium)
type = "flow"
module = "Conv"
repeat = 1
from = [-1]
args.in_channels = 384
args.out_channels = 256
args.kernel_size = 3
args.stride = 1

[[network]]
# 20
type = "flow"
module = "Combine"
repeat = 1
from = [19, 15]

[[network]]
# 21 Detect(P4, P5)
type = "head"
module = "YOLODetect"
repeat = 1
from = [-1]
args.nc = -1
args.from_channels = [256, 512]