# YOLOv3-det model_config.
name = "YOLOv3-det"

scale = "l"

[scales.l]
depth = 1.00
width = 1.00
summary = "333 layers, 98482354 parameters, 98482354 gradients, 262.38 GFLOPs, for a 640×640 input."

# ----------------------------backbone---------------------------------
[[network]]
# 0
type = "entry"
module = "Conv"
repeat = 1
from = [-1]
args.in_channels = 3
args.out_channels = 32
args.kernel_size = 3
args.stride = 1

[[network]]
# 1-P1/2
type = "flow"
module = "Conv"
repeat = 1
from = [-1]
args.in_channels = 32
args.out_channels = 64
args.kernel_size = 3
args.stride = 2

[[network]]
# 2
type = "flow"
module = "Bottleneck"
repeat = 1
from = [-1]
args.in_channels = 64
args.out_channels = 64

[[network]]
# 3-P2/4
type = "flow"
module = "Conv"
repeat = 1
from = [-1]
args.in_channels = 64
args.out_channels = 128
args.kernel_size = 3
args.stride = 2

[[network]]
# 4
type = "flow"
module = "Bottleneck"
repeat = 2
from = [-1]
args.in_channels = 128
args.out_channels = 128

[[network]]
# 5-P3/8
type = "flow"
module = "Conv"
repeat = 1
from = [-1]
args.in_channels = 128
args.out_channels = 256
args.kernel_size = 3
args.stride = 2

[[network]]
# 6
type = "flow"
module = "Bottleneck"
repeat = 8
from = [-1]
args.in_channels = 256
args.out_channels = 256

[[network]]
# 7-P4/16
type = "flow"
module = "Conv"
repeat = 1
from = [-1]
args.in_channels = 256
args.out_channels = 512
args.kernel_size = 3
args.stride = 2

[[network]]
# 8
type = "flow"
module = "Bottleneck"
repeat = 8
from = [-1]
args.in_channels = 512
args.out_channels = 512

[[network]]
# 9-P5/32
type = "flow"
module = "Conv"
repeat = 1
from = [-1]
args.in_channels = 512
args.out_channels = 1024
args.kernel_size = 3
args.stride = 2

[[network]]
# 10
type = "flow"
module = "Bottleneck"
repeat = 4
from = [-1]
args.in_channels = 1024
args.out_channels = 1024

# ----------------------------------head--------------------------------------
[[network]]
# 11
type = "flow"
module = "Bottleneck"
repeat = 1
from = [-1]
args.in_channels = 1024
args.out_channels = 1024
args.shortcut = false

[[network]]
# 12
type = "flow"
module = "Conv"
repeat = 1
from = [-1]
args.in_channels = 1024
args.out_channels = 512
args.kernel_size = 1
args.stride = 1

[[network]]
# 13
type = "flow"
module = "Conv"
repeat = 1
from = [-1]
args.in_channels = 512
args.out_channels = 1024
args.kernel_size = 3
args.stride = 1

[[network]]
# 14
type = "flow"
module = "Conv"
repeat = 1
from = [-1]
args.in_channels = 1024
args.out_channels = 512
args.kernel_size = 1
args.stride = 1

[[network]]
# 15 (P5/32-large)
type = "flow"
module = "Conv"
repeat = 1
from = [-1]
args.in_channels = 512
args.out_channels = 1024
args.kernel_size = 3
args.stride = 1

[[network]]
# 16
type = "flow"
module = "Conv"
repeat = 1
from = [14]
args.in_channels = 512
args.out_channels = 256
args.kernel_size = 1
args.stride = 1

[[network]]
# 17
type = "flow"
module = "torch.nn.Upsample"
repeat = 1
from = [-1]
args.scale_factor = 2
args.mode = "nearest"

[[network]]
# 18 cat backbone P4
type = "flow"
module = "Concat"
repeat = 1
from = [-1, 8]

[[network]]
# 19
type = "flow"
module = "Bottleneck"
repeat = 1
from = [-1]
args.in_channels = 768
args.out_channels = 512
args.shortcut = false

[[network]]
# 20
type = "flow"
module = "Bottleneck"
repeat = 1
from = [-1]
args.in_channels = 512
args.out_channels = 512
args.shortcut = false

[[network]]
# 21
type = "flow"
module = "Conv"
repeat = 1
from = [-1]
args.in_channels = 512
args.out_channels = 256
args.kernel_size = 1
args.stride = 1

[[network]]
# 22 (P4/16-medium)
type = "flow"
module = "Conv"
repeat = 1
from = [-1]
args.in_channels = 256
args.out_channels = 512
args.kernel_size = 3
args.stride = 1

[[network]]
# 23
type = "flow"
module = "Conv"
repeat = 1
from = [21]
args.in_channels = 256
args.out_channels = 128
args.kernel_size = 1
args.stride = 1

[[network]]
# 24
type = "flow"
module = "torch.nn.Upsample"
repeat = 1
from = [-1]
args.scale_factor = 2
args.mode = "nearest"

[[network]]
# 25 cat backbone P3
type = "flow"
module = "Concat"
repeat = 1
from = [-1, 6]

[[network]]
# 26
type = "flow"
module = "Bottleneck"
repeat = 1
from = [-1]
args.in_channels = 384
args.out_channels = 256
args.shortcut = false

[[network]]
# 27 (P3/8-small)
type = "flow"
module = "Bottleneck"
repeat = 2
from = [-1]
args.in_channels = 256
args.out_channels = 256
args.shortcut = false

[[network]]
# 28
type = "flow"
module = "Combine"
repeat = 1
from = [27, 22, 15]

[[network]]
# 29 Detect(P3, P4, P5)
type = "head"
module = "YOLODetect"
repeat = 1
from = [-1]
args.nc = -1
args.from_channels = [256, 512, 1024]