[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "tinytrain"
version = "0.2.3"
description = "A tiny training framework with PyTorch"
readme = "README.md"
requires-python = ">=3.8"
license = { text = "MIT" }
authors = [
    { name = "zycskylove520", email = "867245713@qq.com" }
]
dependencies = [
    "albumentations",
    "chardet",
    "lap",
    "loguru",
    "matplotlib",
    "mmeval",
    "numpy",
    "onnx",
    "onnxruntime",
    "onnxslim",
    "opencv_contrib_python",
    "opencv_python",
    "opencv_python_headless",
    "pandas",
    "Pillow",
    "psutil",
    "ptflops",
    "pycocotools",
    "pydantic",
    "scikit_learn",
    "scipy",
    "seaborn",
    "setproctitle",
    "tabulate",
    "tensorboard",
    "toml",
    "torch",
    "torchmetrics[detection]",
    "torchvision",
]

[project.urls]
Homepage = "https://github.com/yourname/TinyTrain"
Repository = "https://github.com/yourname/TinyTrain"

[tool.setuptools.packages.find]
where = ["."]              # 从当前目录查找
include = ["tinytrain*"]   # 只打包 tinytrain 目录