# ========================
# YOLO图像分类augment配置文件
# ========================

# ==================== 图像读取和数据集裁剪 ====================
rgb = true
# 是否使用RGB图像训练

img_crop_fraction = 1
# 训练数据集裁剪比例：1 表示不裁剪，0.9 表示使用 90% 训练数据集

# ==================== 颜色扰动（ColorJitter） ====================
hsv_h = 0.0
# 色调(Hue)扰动概率：0 表示不扰动

hsv_s = 0.0
# 饱和度(Saturation)扰动概率：0 表示不扰动

hsv_v = 0.0
# 明度(Value/Brightness)扰动概率：0 表示不扰动

color_jitter = 0.0
# 综合颜色扰动的“应用概率”：每幅图有 50% 几率执行 hsv变换

# ==================== 标准化（Normalize） ====================
mean = 0
# 每个通道的均值，用于减均值归一化；0 表示不减均值

std  = 1
# 每个通道的标准差，用于除标准差归一化；1 表示不除标准差

# ==================== 随机缩放裁剪（RandomResizedCrop） ====================
scale = [0.08, 1.0]
# 裁剪后面积与原图面积的比例范围：[最小 8%, 最大 100%]

ratio = [0.75, 1.33]
# 裁剪框宽高比范围：[0.75, 1.33]，即 3:4 ~ 4:3

# ==================== 翻转（Flip） ====================
hflip = 0.0
# 水平翻转概率：0 表示不翻转

vflip = 0.0
# 垂直翻转概率：0 表示不翻转

# ==================== 随机遮挡（Random Erasing） ====================
erasing = 0.0
# 随机遮挡概率：0 表示不遮挡