# MobileFaceNet face recognition model_config.
name = "MobileFaceNet"

scale = "n"

# model_config compound scaling constants
[scales.n]
depth = 0.5
summary = "140 layers, 888576 parameters, 888576 gradients, 0.37 GFLOPs, for a 112×112 input."

[scales.s]
depth = 1
summary = "213 layers, 2066752 parameters, 2066752 gradients, 0.99 GFLOPs, for a 112×112 input."

[scales.m]
depth = 2
summary = "370 layers, 4768320 parameters, 4768320 gradients, 2.47 GFLOPs, for a 112×112 input."

[scales.l]
depth = 3
summary = "526 layers, 8671296 parameters, 8671296 gradients, 4.59 GFLOPs, for a 112×112 input."

[scales.x]
depth = 4
summary = "682 layers, 13775680 parameters, 13775680 gradients, 7.36 GFLOPs, for a 112×112 input."

[scales.xl]
depth = 4
summary = "682 layers, 16443136 parameters, 16443136 gradients, 8.8 GFLOPs, for a 112×112 input."

[scales.xxl]
depth = 4
summary = "682 layers, 19110592 parameters, 19110592 gradients, 10.25 GFLOPs, for a 112×112 input."

# ----------------------------backbone---------------------------------
[[network]]
# 0-P1/2
type = "entry"
module = "Conv"
repeat = 1
from = [-1]
args.in_channels = 3
args.out_channels = 64
args.kernel_size = 3
args.stride = 2
args.padding = 1

[[network]]
# 1
type = "flow"
module = "DWBlock"
allow_repeat = true
repeat = 1
from = [-1]
args.in_channels = 64
args.out_channels = 64
args.kernel_size = 3
args.stride = 1
args.padding = 1
args.groups = 64

[[network]]
# 2
type = "flow"
module = "DWBlock"
repeat = 1
from = [-1]
args.in_channels = 64
args.out_channels = 64
args.kernel_size = 3
args.stride = 2
args.padding = 1
args.groups = 128

[[network]]
# 3
type = "flow"
module = "DWBlock"
repeat = 4
from = [-1]
args.in_channels = 64
args.out_channels = 64
args.kernel_size = 3
args.stride = 1
args.padding = 1
args.groups = 128
args.residual = true

[[network]]
# 4
type = "flow"
module = "DWBlock"
repeat = 1
from = [-1]
args.in_channels = 64
args.out_channels = 128
args.kernel_size = 3
args.stride = 2
args.padding = 1
args.groups = 256

[[network]]
# 5
type = "flow"
module = "DWBlock"
repeat = 6
from = [-1]
args.in_channels = 128
args.out_channels = 128
args.kernel_size = 3
args.stride = 1
args.padding = 1
args.groups = 256
args.residual = true

[[network]]
# 6
type = "flow"
module = "DWBlock"
repeat = 1
from = [-1]
args.in_channels = 128
args.out_channels = 128
args.kernel_size = 3
args.stride = 2
args.padding = 1
args.groups = 512

[[network]]
# 7
type = "flow"
module = "DWBlock"
repeat = 2
from = [-1]
args.in_channels = 128
args.out_channels = 128
args.kernel_size = 3
args.stride = 1
args.padding = 1
args.groups = 256
args.residual = true


# ----------------------------------head--------------------------------------
[[network]]
# 10
type = "head"
module = "GDC"
repeat = 1
from = [-1]
args.in_channels = 128
args.embedding_size = 512
