# Copyright (c) 2025 zycskylove520 - MIT License

# =======================================
# YOLO目标检测模型: YOLOv8-p2-det 模型配置文件
# =======================================

name = "YOLOv8-p2-det"
scale = "n"

# model_config compound scaling constants
[scales.n]
depth = 0.33
width = 0.25
summary = "416 layers, 3576776 parameters, 3576776 gradients, 13.51 GFLOPs, for a 640×640 input."

[scales.s]
depth = 0.33
width = 0.50
summary = "416 layers, 13213304 parameters, 13213304 gradients, 41.4 GFLOPs, for a 640×640 input."

[scales.m]
depth = 0.67
width = 0.75
summary = "508 layers, 35860584 parameters, 35860584 gradients, 106.41 GFLOPs, for a 640×640 input."

[scales.l]
depth = 1.00
width = 1.00
summary = "694 layers, 87336152 parameters, 87336152 gradients, 254.9 GFLOPs, for a 640×640 input."

[scales.x]
depth = 1.00
width = 1.25
summary = "694 layers, 135980744 parameters, 135980744 gradients, 393.94 GFLOPs, for a 640×640 input."

# ----------------------------backbone---------------------------------
[[network]]
# 0-P1/2
type = "entry"
module = "CBA"
repeat = 1
from = [-1]
args.in_channels = 3
args.out_channels = 64
args.kernel_size = 3
args.stride = 2

[[network]]
# 1-P2/4
type = "flow"
module = "CBA"
repeat = 1
from = [-1]
args.in_channels = 64
args.out_channels = 128
args.kernel_size = 3
args.stride = 2

[[network]]
# 2
type = "flow"
module = "C2f"
repeat = 3
from = [-1]
args.in_channels = 128
args.out_channels = 128
args.shortcut = true

[[network]]
# 3-P3/8
type = "flow"
module = "CBA"
repeat = 1
from = [-1]
args.in_channels = 128
args.out_channels = 256
args.kernel_size = 3
args.stride = 2

[[network]]
# 4
type = "flow"
module = "C2f"
repeat = 6
from = [-1]
args.in_channels = 256
args.out_channels = 256
args.shortcut = true

[[network]]
# 5-P4/16
type = "flow"
module = "CBA"
repeat = 1
from = [-1]
args.in_channels = 256
args.out_channels = 512
args.kernel_size = 3
args.stride = 2

[[network]]
# 6
type = "flow"
module = "C2f"
repeat = 6
from = [-1]
args.in_channels = 512
args.out_channels = 512
args.shortcut = true

[[network]]
# 7-P5/32
type = "flow"
module = "CBA"
repeat = 1
from = [-1]
args.in_channels = 512
args.out_channels = 1024
args.kernel_size = 3
args.stride = 2

[[network]]
# 8
type = "flow"
module = "C2f"
repeat = 3
from = [-1]
args.in_channels = 1024
args.out_channels = 1024
args.shortcut = true

[[network]]
# 9
type = "flow"
module = "SPPF"
repeat = 1
from = [-1]
args.in_channels = 1024
args.out_channels = 1024
args.kernel_size = 5

# ----------------------------------head--------------------------------------
[[network]]
# 10
type = "flow"
module = "torch.nn.Upsample"
repeat = 1
from = [-1]
args.scale_factor = 2
args.mode = "nearest"

[[network]]
# 11 cat backbone P4
type = "flow"
module = "Concat"
repeat = 1
from = [-1, 6]

[[network]]
# 12
type = "flow"
module = "C2f"
repeat = 1
from = [-1]
args.in_channels = 1536
args.out_channels = 512

[[network]]
# 13
type = "flow"
module = "C2f"
repeat = 2
from = [-1]
args.in_channels = 512
args.out_channels = 512

[[network]]
# 14
type = "flow"
module = "torch.nn.Upsample"
repeat = 1
from = [-1]
args.scale_factor = 2
args.mode = "nearest"

[[network]]
# 15 cat backbone P3
type = "flow"
module = "Concat"
repeat = 1
from = [-1, 4]

[[network]]
# 16
type = "flow"
module = "C2f"
repeat = 1
from = [-1]
args.in_channels = 768
args.out_channels = 256

[[network]]
# 17
type = "flow"
module = "C2f"
repeat = 2
from = [-1]
args.in_channels = 256
args.out_channels = 256

[[network]]
# 18
type = "flow"
module = "torch.nn.Upsample"
repeat = 1
from = [-1]
args.scale_factor = 2
args.mode = "nearest"

[[network]]
# 19 cat backbone P2
type = "flow"
module = "Concat"
repeat = 1
from = [-1, 2]

[[network]]
# 20
type = "flow"
module = "C2f"
repeat = 1
from = [-1]
args.in_channels = 384
args.out_channels = 128

[[network]]
# 21 (P2/4-xsmall)
type = "flow"
module = "C2f"
repeat = 2
from = [-1]
args.in_channels = 128
args.out_channels = 128

[[network]]
# 22
type = "flow"
module = "CBA"
repeat = 1
from = [-1]
args.in_channels = 128
args.out_channels = 128
args.kernel_size = 3
args.stride = 2

[[network]]
# 23 cat head P3
type = "flow"
module = "Concat"
repeat = 1
from = [-1, 17]

[[network]]
# 24
type = "flow"
module = "C2f"
repeat = 1
from = [-1]
args.in_channels = 384
args.out_channels = 256

[[network]]
# 25 (P3/8-small)
type = "flow"
module = "C2f"
repeat = 2
from = [-1]
args.in_channels = 256
args.out_channels = 256

[[network]]
# 26
type = "flow"
module = "CBA"
repeat = 1
from = [-1]
args.in_channels = 256
args.out_channels = 256
args.kernel_size = 3
args.stride = 2

[[network]]
# 27 cat head P4
type = "flow"
module = "Concat"
repeat = 1
from = [-1, 13]

[[network]]
# 28
type = "flow"
module = "C2f"
repeat = 1
from = [-1]
args.in_channels = 768
args.out_channels = 512

[[network]]
# 29 (P4/16-medium)
type = "flow"
module = "C2f"
repeat = 2
from = [-1]
args.in_channels = 512
args.out_channels = 512

[[network]]
# 30
type = "flow"
module = "CBA"
repeat = 1
from = [-1]
args.in_channels = 512
args.out_channels = 512
args.kernel_size = 3
args.stride = 2

[[network]]
# 31 cat head P5
type = "flow"
module = "Concat"
repeat = 1
from = [-1, 9]

[[network]]
# 32
type = "flow"
module = "C2f"
repeat = 1
from = [-1]
args.in_channels = 1536
args.out_channels = 1024

[[network]]
# 33 (P4/16-medium)
type = "flow"
module = "C2f"
repeat = 2
from = [-1]
args.in_channels = 1024
args.out_channels = 1024

[[network]]
# 34
type = "flow"
module = "Combine"
repeat = 1
from = [21, 25, 29, 33]

[[network]]
# 35 Detect(P2, P3, P4, P5)
type = "head"
module = "YOLODetectHead"
repeat = 1
from = [-1]
args.nc = -1
args.from_channels = [128, 256, 512, 1024]