# YOLOv12-det model_config.
name = "YOLOv12-det"

scale = "n"

# model_config compound scaling constants
[scales.n]
depth = 0.50
width = 0.25
summary = "464 layers, 2568227 parameters, 2568227 gradients, 6.44 GFLOPs, for a 640×640 input."

[scales.s]
depth = 0.50
width = 0.50
summary = "464 layers, 9253507 parameters, 9253507 gradients, 21.44 GFLOPs, for a 640×640 input."

[scales.m]
depth = 0.50
width = 1.00
summary = "500 layers, 35388675 parameters, 35388675 gradients, 80.09 GFLOPs, for a 640×640 input."

[scales.l]
depth = 1.00
width = 1.00
summary = "830 layers, 48820883 parameters, 48820883 gradients, 107.42 GFLOPs, for a 640×640 input."

[scales.x]
depth = 1.00
width = 1.50
summary = "830 layers, 109483891 parameters, 109483891 gradients, 240.45 GFLOPs, for a 640×640 input."

# ----------------------------backbone---------------------------------
[[network]]
# 0-P1/2
type = "entry"
module = "Conv"
repeat = 1
from = [-1]
args.in_channels = 3
args.out_channels = 64
args.kernel_size = 3
args.stride = 2

[[network]]
# 1-P2/4
type = "flow"
module = "Conv"
repeat = 1
from = [-1]
args.in_channels = 64
args.out_channels = 128
args.kernel_size = 3
args.stride = 2

[[network]]
# 2
type = "flow"
module = "C3k2"
repeat = 1
from = [-1]
args.in_channels = 128
args.out_channels = 256
args.n = 2
args.c3k = false
args.hidden_channels = 0.25

[[network]]
# 3-P3/8
type = "flow"
module = "Conv"
repeat = 1
from = [-1]
args.in_channels = 256
args.out_channels = 256
args.kernel_size = 3
args.stride = 2

[[network]]
# 4
type = "flow"
module = "C3k2"
repeat = 1
from = [-1]
args.in_channels = 256
args.out_channels = 512
args.n = 2
args.c3k = false
args.hidden_channels = 0.25

[[network]]
type = "flow"
# 5-P4/16
module = "Conv"
repeat = 1
from = [-1]
args.in_channels = 512
args.out_channels = 512
args.kernel_size = 3
args.stride = 2

[[network]]
type = "flow"
# 6
module = "A2C2f"
repeat = 1
from = [-1]
args.in_channels = 512
args.out_channels = 512
args.n = 4
args.a2 = true
args.area = 4

[[network]]
type = "flow"
# 7-P5/32
module = "Conv"
repeat = 1
from = [-1]
args.in_channels = 512
args.out_channels = 1024
args.kernel_size = 3
args.stride = 2

[[network]]
type = "flow"
# 8
module = "A2C2f"
repeat = 1
from = [-1]
args.in_channels = 1024
args.out_channels = 1024
args.n = 4
args.a2 = true
args.area = 1

# ----------------------------------head--------------------------------------
[[network]]
# 9
type = "flow"
module = "torch.nn.Upsample"
repeat = 1
from = [-1]
args.scale_factor = 2
args.mode = "nearest"

[[network]]
# 10 cat backbone P4
type = "flow"
module = "Concat"
repeat = 1
from = [-1, 6]
args.dimension = 1

[[network]]
type = "flow"
# 11
module = "A2C2f"
repeat = 1
from = [-1]
args.in_channels = 1536
args.out_channels = 512
args.n = 2
args.a2 = false
args.area = -1

[[network]]
# 12
type = "flow"
module = "torch.nn.Upsample"
repeat = 1
from = [-1]
args.scale_factor = 2
args.mode = "nearest"

[[network]]
# 13 cat backbone P3
type = "flow"
module = "Concat"
repeat = 1
from = [-1, 4]
args.dimension = 1

[[network]]
type = "flow"
# 14 (P3/8-small)
module = "A2C2f"
repeat = 1
from = [-1]
args.in_channels = 1024
args.out_channels = 256
args.n = 2
args.a2 = false
args.area = -1

[[network]]
type = "flow"
# 15
module = "Conv"
repeat = 1
from = [-1]
args.in_channels = 256
args.out_channels = 256
args.kernel_size = 3
args.stride = 2

[[network]]
# 16 cat head P4
type = "flow"
module = "Concat"
repeat = 1
from = [-1, 11]
args.dimension = 1

[[network]]
type = "flow"
# 17 (P4/16-medium)
module = "A2C2f"
repeat = 1
from = [-1]
args.in_channels = 768
args.out_channels = 512
args.n = 2
args.a2 = false
args.area = -1

[[network]]
type = "flow"
# 18
module = "Conv"
repeat = 1
from = [-1]
args.in_channels = 512
args.out_channels = 512
args.kernel_size = 3
args.stride = 2

[[network]]
# 19 cat head P5
type = "flow"
module = "Concat"
repeat = 1
from = [-1, 8]
args.dimension = 1

[[network]]
# 20 (P5/32-large)
type = "flow"
module = "C3k2"
repeat = 1
from = [-1]
args.in_channels = 1536
args.out_channels = 1024
args.n = 2
args.c3k = true

[[network]]
# 21
type = "flow"
module = "Combine"
repeat = 1
from = [14, 17, 20]

[[network]]
# 22 Detect(P3, P4, P5)
type = "head"
module = "YOLODetect"
repeat = 1
from = [-1]
args.nc = -1
args.from_channels = [256, 512, 1024]


