cls_loss_gain = 0.5  # 分类损失权重：放大或缩小分类 loss 对总梯度的贡献，0.5 表示最终分类 loss ×0.5
box_loss_gain = 7.5  # 边界框回归损失权重：提高框位置精度在训练中的重要性，7.5 表示框 loss ×7.5
dfl_loss_gain = 1.5  # Distribution Focal Loss（分布焦点损失）权重：用于更精细的框定位，1.5 表示 dfl loss ×1.5