img_size = 32
cache = true
path = "datasets/mnist"

train = "train"
val = "val"
test = ""

nc = 10
[names]
0 = "airplane"
1 = "automobile"
2 = "bird"
3 = "cat"
4 = "deer"
5 = "dog"
6 = "frog"
7 = "horse"
8 = "ship"
9 = "truck"
