# YOLO11-cls image classification model_config.

scale = "n"

# model_config compound scaling constants
[scales.n]
depth = 0.50
width = 0.25
max_channels = 1024
summary = "151 layers, 1633584 parameters, 1633584 gradients, 3.3 GFLOPs"

[scales.s]
depth = 0.50
width = 0.50
max_channels = 1024
summary = "151 layers, 5545488 parameters, 5545488 gradients, 12.2 GFLOPs"

[scales.m]
depth = 0.50
width = 1.00
max_channels = 512
summary = "187 layers, 10455696 parameters, 10455696 gradients, 39.7 GFLOPs"

[scales.l]
depth = 1.00
width = 1.00
max_channels = 512
summary = "309 layers, 12937104 parameters, 12937104 gradients, 49.9 GFLOPs"

[scales.x]
depth = 1.00
width = 1.50
max_channels = 512
summary = "309 layers, 28458544 parameters, 28458544 gradients, 111.1 GFLOPs"

# YOLO11n-cls backbone
[[network]]
# 0-P1/2
type = "entry"
module = "Conv"
repeat = 1
from = [-1]
args.in_channels = 3
args.out_channels = 64
args.kernel_size = 3
args.stride = 2

[[network]]
# 1-P2/4
type = "flow"
module = "Conv"
repeat = 1
from = [-1]
args.in_channels = 64
args.out_channels = 128
args.kernel_size = 3
args.stride = 2

[[network]]
type = "flow"
module = "C3k2"
repeat = 1
from = [-1]
args.in_channels = 128
args.out_channels = 256
args.n = 2
args.c3k = false
args.hidden_channels = 0.25

[[network]]
# 3-P3/8
type = "flow"
module = "Conv"
repeat = 1
from = [-1]
args.in_channels = 256
args.out_channels = 256
args.kernel_size = 3
args.stride = 2

[[network]]
type = "flow"
module = "C3k2"
repeat = 1
from = [-1]
args.in_channels = 256
args.out_channels = 512
args.n = 2
args.c3k = false
args.hidden_channels = 0.25

[[network]]
type = "flow"
# 5-P4/16
module = "Conv"
repeat = 1
from = [-1]
args.in_channels = 512
args.out_channels = 512
args.kernel_size = 3
args.stride = 2

[[network]]
type = "flow"
module = "C3k2"
repeat = 1
from = [-1]
args.in_channels = 512
args.out_channels = 512
args.n = 2
args.c3k = true

[[network]]
type = "flow"
# 7-P5/32
module = "Conv"
repeat = 1
from = [-1]
args.in_channels = 512
args.out_channels = 1024
args.kernel_size = 3
args.stride = 2

[[network]]
type = "flow"
module = "C3k2"
repeat = 1
from = [-1]
args.in_channels = 1024
args.out_channels = 1024
args.n = 2
args.c3k = true

[[network]]
type = "flow"
# 9
module = "C2PSA"
repeat = 1
from = [-1]
args.in_channels = 1024
args.out_channels = 1024

# YOLO11n-cls head
[[network]]
type = "head"
module = "Classify"
repeat = 1
from = [-1]
args.in_channels = 1024
args.nc = -1