# =====================
# YOLO姿态估计loss配置文件
# =====================

cls_loss_gain = 0.5
# 分类损失权重，用于平衡分类任务在总损失中的占比，值为 0.5

box_loss_gain = 7.5
# 边界框回归损失权重，用于调整边界框预测任务在总损失中的比重，值为 7.5

dfl_loss_gain = 1.5
# 分布式焦点损失权重，通常用于目标检测中的分类分支，值为 1.5

seg_loss_gain = 12.0
# 姿态估计损失权重，用于姿态估计任务在总损失中的权重，值为 12.0