# ========================
# YOLO目标检测augment配置文件
# ========================

# ==================== 图像读取与数据集裁剪 ====================
rgb = true
# 是否使用RGB图像训练

img_crop_fraction = 1
# 训练数据集裁剪比例：1 表示不裁剪，0.9 表示使用 90% 训练数据集

# ==================== 颜色扰动（ColorJitter） ====================
hsv_h = 0.0
# 色调(Hue)扰动概率：0 表示不扰动

hsv_s = 0.0
# 饱和度(Saturation)扰动概率：0 表示不扰动

hsv_v = 0.0
# 明度(Value/Brightness)扰动概率：0 表示不扰动

color_jitter = 0.0
# 综合颜色扰动的“应用概率”：每幅图有 50% 几率执行 hsv变换

# ==================== 标准化（Normalize） ====================
mean = 0
# 每个通道的均值，用于减均值归一化；0 表示不减均值

std  = 1
# 每个通道的标准差，用于除标准差归一化；1 表示不除标准差

# ==================== 翻转（Flip） ====================
hflip = 0.0
# 水平翻转概率：0 表示不翻转

vflip = 0.0
# 垂直翻转概率：0 表示不翻转

# ==================== 仿射变换（Affine） ====================
scale = [0.8, 1.2]
# 随机缩放比例：浮点数；>0；推荐 0.3‒3.0 以内，此处限定 0.8‒1.2

translate = [-0.2, 0.2]
# 随机平移概率：浮点数；[-1.0, 1.0] 之间，-1 表示全图宽/高，此处限定 ±0.2

rotate = [-15, 15]
# 随机旋转概率：浮点数；[-360, 360] 度之间，此处限定 ±15°

shear = [-5, 5]
# 随机错切概率：浮点数；[-360, 360] 度之间，合理区间 ±45°，此处限定 ±5°