# track
min_box_area = 100      # 跟踪的最小目标面积
track_threshold = 0.25  # 跟踪置信度阈值
track_buffer = 30    # 最大目标丢失帧数，超过该值则认为目标丢失
match_threshold = 0.9  # 跟踪目标匹配阈值

# save
show_realtime_result = false  # 是否实时战死跟踪结果
save_img = false  # 保存跟踪结果每一帧的图片
save_video = false  # 保存跟踪结果视频
save_video_fps = 24  # 保存的跟踪结果视频的帧率
