# Copyright (c) 2025 zycskylove520 - MIT License

# ========================
# YOLO图像分类dataset配置文件
# ========================

img_size = 32
# 输入图像的尺寸，模型将图像缩放到这个大小进行处理

cache = false
# 是否使用缓存，设置为 false 表示不使用缓存

train = "datasets/mnist/train"
# 训练集图像路径

val = "datasets/mnist/val"
# 验证集图像路径

nc = 10
# 数据集的类别数量

# 类别名称(可选)，如果不写，则自动生成
[names]
0 = "0"
1 = "1"
2 = "2"
3 = "3"
4 = "4"
5 = "5"
6 = "6"
7 = "7"
8 = "8"
9 = "9"
