# ====================
# 车牌识别dataset配置文件
# ====================

img_size = [94, 24]
# 输入图像的尺寸，模型将图像缩放到这个大小进行处理
# 模型目前仅支持[94, 24]尺寸，请勿修改尺寸

cache = false
# 是否使用缓存，设置为 false 表示不使用缓存

train = "datasets/mnist/train"
# 训练集图像路径

val = "datasets/mnist/val"
# 验证集图像路径

test = ""
# 测试集图像路径，留空表示没有测试集

lpr_max_len = 8
# 车牌字符最大长度

nc = 76
# 数据集的类别数量

# 类别名称(可选)，如果不写，则自动生成
[names]
0 = '临'
1 = '云'
2 = '京'
3 = '使'
4 = '冀'
5 = '吉'
6 = '学'
7 = '宁'
8 = '川'
9 = '挂'
10 = '新'
11 = '晋'
12 = '桂'
13 = '沪'
14 = '津'
15 = '浙'
16 = '渝'
17 = '港'
18 = '湘'
19 = '澳'
20 = '琼'
21 = '甘'
22 = '皖'
23 = '粤'
24 = '苏'
25 = '蒙'
26 = '藏'
27 = '警'
28 = '豫'
29 = '贵'
30 = '赣'
31 = '辽'
32 = '鄂'
33 = '闽'
34 = '陕'
35 = '青'
36 = '领'
37 = '鲁'
38 = '黑'
39 = '0'
40 = '1'
41 = '2'
42 = '3'
43 = '4'
44 = '5'
45 = '6'
46 = '7'
47 = '8'
48 = '9'
49 = 'A'
50 = 'B'
51 = 'C'
52 = 'D'
53 = 'E'
54 = 'F'
55 = 'G'
56 = 'H'
57 = 'J'
58 = 'K'
59 = 'L'
60 = 'M'
61 = 'N'
62 = 'P'
63 = 'Q'
64 = 'R'
65 = 'S'
66 = 'T'
67 = 'U'
68 = 'V'
69 = 'W'
70 = 'X'
71 = 'Y'
72 = 'Z'
73 = 'I'
74 = 'O'
75 = '-'
