# ====================
# 车牌识别dataset配置文件
# ====================

img_size = [94, 24]
# 输入图像的尺寸，模型将图像缩放到这个大小进行处理
# 模型目前仅支持[94, 24]尺寸，请勿修改尺寸

cache = false
# 是否使用缓存，设置为 false 表示不使用缓存

train = "datasets/mnist/train"
# 训练集图像路径

val = "datasets/mnist/val"
# 验证集图像路径

test = ""
# 测试集图像路径，留空表示没有测试集

lpr_max_len = 18
# 车牌字符最大长度，要求：lpr_max_len <= img_size_w // 4

nc = 70
# 数据集的类别数量

# 类别名称(可选)，如果不写，则自动生成
[names]
0 = '京'
1 = '沪'
2 = '津'
3 = '渝'
4 = '冀'
5 = '晋'
6 = '蒙'
7 = '辽'
8 = '吉'
9 = '黑'
10 = '苏'
11 = '浙'
12 = '皖'
13 = '闽'
14 = '赣'
15 = '鲁'
16 = '豫'
17 = '鄂'
18 = '湘'
19 = '粤'
20 = '桂'
21 = '琼'
22 = '川'
23 = '贵'
24 = '云'
25 = '藏'
26 = '陕'
27 = '甘'
28 = '青'
29 = '宁'
30 = '新'
31 = '警'
32 = '学'
33 = '0'
34 = '1'
35 = '2'
36 = '3'
37 = '4'
38 = '5'
39 = '6'
40 = '7'
41 = '8'
42 = '9'
43 = 'A'
44 = 'B'
45 = 'C'
46 = 'D'
47 = 'E'
48 = 'F'
49 = 'G'
50 = 'H'
51 = 'J'
52 = 'K'
53 = 'L'
54 = 'M'
55 = 'N'
56 = 'P'
57 = 'Q'
58 = 'R'
59 = 'S'
60 = 'T'
61 = 'U'
62 = 'V'
63 = 'W'
64 = 'X'
65 = 'Y'
66 = 'Z'
67 = 'I'
68 = 'O'
69 = '-'
