# Copyright (c) 2025 zycskylove520 - MIT License

# =======================================
# YOLO目标检测模型: YOLOv5-p6-det 模型配置文件
# =======================================

name = "YOLOv5-p6-det"
scale = "n"

# model_config compound scaling constants
[scales.n]
depth = 0.33
width = 0.25
summary = "500 layers, 4485112 parameters, 4485112 gradients, 7.14 GFLOPs, for a 640×640 input."

[scales.s]
depth = 0.33
width = 0.50
summary = "500 layers, 16638680 parameters, 16638680 gradients, 23.8 GFLOPs, for a 640×640 input."

[scales.m]
depth = 0.67
width = 0.75
summary = "685 layers, 43987704 parameters, 43987704 gradients, 69.55 GFLOPs, for a 640×640 input."

[scales.l]
depth = 1.00
width = 1.00
summary = "941 layers, 101828248 parameters, 101828248 gradients, 163.73 GFLOPs, for a 640×640 input."

[scales.x]
depth = 1.33
width = 1.25
summary = "1193 layers, 196993720 parameters, 196993720 gradients, 321.34 GFLOPs, for a 640×640 input."

# ----------------------------backbone---------------------------------
[[network]]
# 0-P1/2
type = "entry"
module = "CBA"
repeat = 1
from = [-1]
args.in_channels = 3
args.out_channels = 64
args.kernel_size = 6
args.stride = 2
args.padding = 2

[[network]]
# 1-P2/4
type = "flow"
module = "CBA"
repeat = 1
from = [-1]
args.in_channels = 64
args.out_channels = 128
args.kernel_size = 3
args.stride = 2

[[network]]
# 2
type = "flow"
module = "C3"
repeat = 3
from = [-1]
args.in_channels = 128
args.out_channels = 128

[[network]]
# 3-P3/8
type = "flow"
module = "CBA"
repeat = 1
from = [-1]
args.in_channels = 128
args.out_channels = 256
args.kernel_size = 3
args.stride = 2

[[network]]
# 4
type = "flow"
module = "C3"
repeat = 6
from = [-1]
args.in_channels = 256
args.out_channels = 256

[[network]]
# 5-P4/16
type = "flow"
module = "CBA"
repeat = 1
from = [-1]
args.in_channels = 256
args.out_channels = 512
args.kernel_size = 3
args.stride = 2

[[network]]
# 6
type = "flow"
module = "C3"
repeat = 9
from = [-1]
args.in_channels = 512
args.out_channels = 512

[[network]]
# 7-P5/32
type = "flow"
module = "CBA"
repeat = 1
from = [-1]
args.in_channels = 512
args.out_channels = 768
args.kernel_size = 3
args.stride = 2

[[network]]
# 8
type = "flow"
module = "C3"
repeat = 3
from = [-1]
args.in_channels = 768
args.out_channels = 768

[[network]]
# 9-P6/64
type = "flow"
module = "CBA"
repeat = 1
from = [-1]
args.in_channels = 768
args.out_channels = 1024
args.kernel_size = 3
args.stride = 2

[[network]]
# 10
type = "flow"
module = "C3"
repeat = 3
from = [-1]
args.in_channels = 1024
args.out_channels = 1024

[[network]]
# 11
type = "flow"
module = "SPPF"
repeat = 1
from = [-1]
args.in_channels = 1024
args.out_channels = 1024
args.kernel_size = 5

# ----------------------------------head--------------------------------------
[[network]]
# 12
type = "flow"
module = "CBA"
repeat = 1
from = [-1]
args.in_channels = 1024
args.out_channels = 768
args.kernel_size = 1
args.stride = 1

[[network]]
# 13
type = "flow"
module = "torch.nn.Upsample"
repeat = 1
from = [-1]
args.scale_factor = 2
args.mode = "nearest"

[[network]]
# 14 cat backbone P5
type = "flow"
module = "Concat"
repeat = 1
from = [-1, 8]

[[network]]
# 15
type = "flow"
module = "C3"
repeat = 1
from = [-1]
args.in_channels = 1536
args.out_channels = 768
args.shortcut = false

[[network]]
# 16
type = "flow"
module = "C3"
repeat = 2
from = [-1]
args.in_channels = 768
args.out_channels = 768
args.shortcut = false

[[network]]
# 17
type = "flow"
module = "CBA"
repeat = 1
from = [-1]
args.in_channels = 768
args.out_channels = 512
args.kernel_size = 1
args.stride = 1

[[network]]
# 18
type = "flow"
module = "torch.nn.Upsample"
repeat = 1
from = [-1]
args.scale_factor = 2
args.mode = "nearest"

[[network]]
# 19 cat backbone P4
type = "flow"
module = "Concat"
repeat = 1
from = [-1, 6]

[[network]]
# 20
type = "flow"
module = "C3"
repeat = 1
from = [-1]
args.in_channels = 1024
args.out_channels = 512
args.shortcut = false

[[network]]
# 21
type = "flow"
module = "C3"
repeat = 2
from = [-1]
args.in_channels = 512
args.out_channels = 512
args.shortcut = false

[[network]]
# 22
type = "flow"
module = "CBA"
repeat = 1
from = [-1]
args.in_channels = 512
args.out_channels = 256
args.kernel_size = 1
args.stride = 1

[[network]]
# 23
type = "flow"
module = "torch.nn.Upsample"
repeat = 1
from = [-1]
args.scale_factor = 2
args.mode = "nearest"

[[network]]
# 24 cat backbone P3
type = "flow"
module = "Concat"
repeat = 1
from = [-1, 4]

[[network]]
# 25
type = "flow"
module = "C3"
repeat = 1
from = [-1]
args.in_channels = 512
args.out_channels = 256
args.shortcut = false

[[network]]
# 26 (P3/8-small)
type = "flow"
module = "C3"
repeat = 3
from = [-1]
args.in_channels = 256
args.out_channels = 256
args.shortcut = false

[[network]]
# 27
type = "flow"
module = "CBA"
repeat = 1
from = [-1]
args.in_channels = 256
args.out_channels = 256
args.kernel_size = 3
args.stride = 2

[[network]]
# 28 cat head P4
type = "flow"
module = "Concat"
repeat = 1
from = [-1, 22]

[[network]]
# 29 (P4/16-medium)
type = "flow"
module = "C3"
repeat = 3
from = [-1]
args.in_channels = 512
args.out_channels = 512
args.shortcut = false

[[network]]
# 30
type = "flow"
module = "CBA"
repeat = 1
from = [-1]
args.in_channels = 512
args.out_channels = 512
args.kernel_size = 3
args.stride = 2

[[network]]
# 31 cat head P5
type = "flow"
module = "Concat"
repeat = 1
from = [-1, 17]

[[network]]
# 32
type = "flow"
module = "C3"
repeat = 1
from = [-1]
args.in_channels = 1024
args.out_channels = 768
args.shortcut = false

[[network]]
# 33 (P5/32-large)
type = "flow"
module = "C3"
repeat = 2
from = [-1]
args.in_channels = 768
args.out_channels = 768
args.shortcut = false

[[network]]
# 34
type = "flow"
module = "CBA"
repeat = 1
from = [-1]
args.in_channels = 768
args.out_channels = 768
args.kernel_size = 3
args.stride = 2

[[network]]
# 35 cat head P6
type = "flow"
module = "Concat"
repeat = 1
from = [-1, 12]

[[network]]
# 36
type = "flow"
module = "C3"
repeat = 1
from = [-1]
args.in_channels = 1536
args.out_channels = 1024
args.shortcut = false

[[network]]
# 37 (P6/64-xlarge)
type = "flow"
module = "C3"
repeat = 2
from = [-1]
args.in_channels = 1024
args.out_channels = 1024
args.shortcut = false

[[network]]
# 38
type = "flow"
module = "Combine"
repeat = 1
from = [26, 29, 33, 37]

[[network]]
# 39 Detect(P3, P4, P5, P6)
type = "head"
module = "YOLODetectHead"
repeat = 1
from = [-1]
args.nc = -1
args.from_channels = [256, 512, 768, 1024]