core = "cfg/core.toml"
model = "cfg/model/v11/yolov11-pose.toml"
loss = "cfg/loss-pose.toml"
dataset = "cfg/dataset-pose.toml"
augment = "cfg/augment-pose.toml"
inference="cfg/inference-pose.toml"
tracker="cfg/byte_tracker.toml"