# ==========================
# ByteTracker目标跟踪tracker配置文件
# ==========================

# 跟踪相关参数
min_box_area = 100
# 跟踪的最小目标面积，小于该面积的目标将被忽略

track_threshold = 0.25
# 跟踪置信度阈值，低于该阈值的目标将不被跟踪

track_buffer = 30
# 最大目标丢失帧数，超过该值则认为目标丢失

match_threshold = 0.9
# 跟踪目标匹配阈值，用于判断目标是否匹配成功

# 保存相关参数
show_realtime_result = false
# 是否实时显示跟踪结果，设置为 false 表示不实时显示

save_img = false
# 是否保存跟踪结果每一帧的图片，设置为 false 表示不保存

save_video = true
# 是否保存跟踪结果视频，设置为 true 表示保存

save_video_fps = 24
# 保存的跟踪结果视频的帧率，单位为帧/秒
